services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - "./data/mongodb:/data/db"
    networks:
      - paperly

networks:
  paperly: