services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - "./data/mongodb:/data/db"
    networks:
      - paperly

  minio:
    image: minio/minio:latest
    container_name: paperly-minio
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    entrypoint:
      - /bin/sh
      - -c
      - |
        mkdir -p /data/paperly
        minio server /data --console-address ":9001" &
        sleep 5
        mc alias set local http://localhost:9000 minioadmin minioadmin
        mc anonymous set public local/paperly
        wait
    volumes:
      - ./minio:/data
    networks:
      - paperly
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  paperly: